// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGNpIEh2zxtq4TtCfnj_lSaA_r4UhwtXg',
    appId: '1:389744187523:web:fa2ccca9c570ae2f2e23b6',
    messagingSenderId: '389744187523',
    projectId: 'savelt',
    authDomain: 'savelt.firebaseapp.com',
    storageBucket: 'savelt.firebasestorage.app',
    measurementId: 'G-RDEBNF0C2Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpOXIar8LjkwCPadOpZKokIxKU84LthTA',
    appId: '1:389744187523:android:920ca8a9a13fc5d02e23b6',
    messagingSenderId: '389744187523',
    projectId: 'savelt',
    storageBucket: 'savelt.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTNK3Hm4z1rDee-jTB-ME5tEX83uTa4nM',
    appId: '1:389744187523:ios:57b7520f17a44ec02e23b6',
    messagingSenderId: '389744187523',
    projectId: 'savelt',
    storageBucket: 'savelt.firebasestorage.app',
    iosBundleId: 'com.example.savelt4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTNK3Hm4z1rDee-jTB-ME5tEX83uTa4nM',
    appId: '1:389744187523:ios:57b7520f17a44ec02e23b6',
    messagingSenderId: '389744187523',
    projectId: 'savelt',
    storageBucket: 'savelt.firebasestorage.app',
    iosBundleId: 'com.example.savelt4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGNpIEh2zxtq4TtCfnj_lSaA_r4UhwtXg',
    appId: '1:389744187523:web:578d7927830c5dc72e23b6',
    messagingSenderId: '389744187523',
    projectId: 'savelt',
    authDomain: 'savelt.firebaseapp.com',
    storageBucket: 'savelt.firebasestorage.app',
    measurementId: 'G-C6MHQ7N3BR',
  );
}
